# Generated by Django 4.1.7 on 2023-03-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_remove_cook_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['id']},
        ),
    ]
