# Generated by Django 4.1.7 on 2023-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_dishtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
