# Generated by Django 4.1.7 on 2023-03-29 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_cook_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ['-years_of_experience'], 'verbose_name': 'cook', 'verbose_name_plural': 'cooks'},
        ),
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
